-- Create user_profiles table
CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    education TEXT NOT NULL,
    skills TEXT NOT NULL,
    interests TEXT NOT NULL,
    experience TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create ai_outputs table
CREATE TABLE ai_outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    career_roles JSONB,
    missing_skills JSONB,
    certifications JSONB,
    projects JSONB,
    resume TEXT,
    roadmap JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optional: Enable RLS (Row Level Security)
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_outputs ENABLE ROW LEVEL SECURITY;
